import type { PortfolioData } from './types'

export const portfolioData: PortfolioData = {
  person: {
    name: '磨海清',
    role: 'RAG / Agent 应用工程实习生',
    headline: '把 AI 原型做成可验证的产品。',
    introduction: '专注本地优先 RAG、Agent 与 AI 全栈应用，从检索质量推进到桌面交付。',
    email: '3230390742@qq.com',
    githubUrl: 'https://github.com/3230390742',
    resumeUrl: '/resume/磨海清_AI应用工程实习简历.pdf',
  },
  heroMetrics: [
    { value: '3,827', label: '知识分块' },
    { value: '0.084s', label: '启动扫描' },
    { value: '64/64', label: 'MCP 测试' },
  ],
  featuredProjects: [
    {
      id: 'personal-rag',
      title: '个人 RAG 知识库',
      status: 'Active',
      period: '2026.06 - 至今',
      role: '个人项目负责人',
      summary: '围绕 Obsidian Vault 构建本地优先知识库，并交付 React + FastAPI 桌面应用与 Windows 安装器。',
      problem: '研究资料与个人记忆需要统一检索，但个人内容必须保持 local-only，且桌面应用需要在真实 Windows 生命周期中稳定启动。',
      constraints: ['个人记忆不得离开本机', '中文检索需要混合召回与重排', '安装、升级与卸载必须可验证'],
      decisions: ['按 ai_research / personal_memory 划分 profile', '建立 Provider Client Pool 与 generation-safe 热重载', '通过 SSE 暴露 progress / timing 事件'],
      implementation: ['多格式解析、混合检索、重排和来源引用', 'React + FastAPI 桌面壳与 PyInstaller 打包', '前后端、隐私和真实启动质量门'],
      results: [
        { value: '175 → 164', label: '输入审核与合格记忆' },
        { value: '3,827', label: '最终分块' },
        { value: '7.44s → 0.084s', label: '启动扫描优化' },
        { value: '5 次', label: '真实生命周期验证' },
      ],
      stack: ['Python', 'FastAPI', 'Qdrant', 'React', 'Vite', 'PyInstaller'],
      evidence: ['真实应用界面', '连续生命周期验证', '启动 timing 记录'],
      visuals: [
        { kind: 'image', src: '/media/projects/personal-rag-ai-research.png', alt: '个人 RAG 知识库的 AI research 界面', caption: 'AI research profile：检索、来源与运行状态' },
        { kind: 'image', src: '/media/projects/personal-rag-memory.png', alt: '个人 RAG 知识库的 personal memory 界面', caption: 'Personal memory profile：local-only 记忆管理' },
        { kind: 'video', src: '/media/projects/personal-rag-demo.mp4', poster: '/media/projects/personal-rag-ai-research.png', title: '个人 RAG 知识库演示', caption: '本地应用与知识检索演示' },
      ],
    },
    {
      id: 'local-agent-mcp',
      title: 'Local Agent MCP',
      status: 'Verified',
      period: '2026.07',
      role: '个人项目主导（AI 辅助）',
      summary: '实现本地 stdio MCP Agent Hub，为编排端提供运行、对比和健康检查工具。',
      problem: '本地编排器需要调用多个编码 Agent，但工作目录、并发、输出和密钥边界不能依赖调用者自觉。',
      constraints: ['默认只读', '不得通过 shell 插值执行命令', '同目录写操作必须串行'],
      decisions: ['realpath allowlist 校验真实路径', '固定 shell:false 并限制输出与超时', '同目录写锁与全局并发限制组合'],
      implementation: ['Codex / OpenCode 运行与结果对比工具', '健康检查与结构化 Zod 输入', '密钥脱敏、超时和输出上限'],
      results: [
        { value: '4 类', label: 'MCP 工具' },
        { value: '8', label: '测试文件' },
        { value: '64/64', label: '测试通过' },
      ],
      stack: ['TypeScript', 'MCP SDK', 'Zod', 'Vitest', 'Node.js'],
      evidence: ['Fresh Vitest 结果', 'TypeScript typecheck', '安全边界测试'],
      visuals: [{ kind: 'evidence', title: '安全执行边界', lines: ['realpath allowlist', 'read-only default', 'shell:false', 'same-directory write lock', 'sensitive-value redaction', '64/64 tests'] }],
    },
    {
      id: 'ai-ui-regression',
      title: 'AI UI 回归审计',
      status: 'Audited',
      period: '2026.07',
      role: '证据链与实现负责人',
      summary: '结合真实浏览器截图、像素差、DOM 语义、布局几何和对比度规则审计两版界面。',
      problem: '纯截图差异无法可靠解释按钮缺失、语义漂移或移动端遮挡，审计还必须避免检测器偷看私有真值。',
      constraints: ['全流程本地且零外联', '检测器与私有真值隔离', '每个 finding 必须绑定公开像素与语义证据'],
      decisions: ['Playwright 双视口确定性捕获', '像素差与通用语义规则组合', 'findings 锁定后再读取私有真值终审'],
      implementation: ['桌面与手机基线 / 候选捕获', '六类语义、布局和对比度检测', '自包含离线交互报告与哈希审计'],
      results: [
        { value: '6/6', label: '单原因回归识别' },
        { value: '2', label: '允许变化零误报' },
        { value: '1.0', label: 'Precision / Recall / F1' },
      ],
      stack: ['Python', 'Playwright', 'Pixel Diff', 'DOM', 'WCAG'],
      evidence: ['确定性浏览器截图', '公开 findings 与差异区域', '私有真值终审'],
      visuals: [
        { kind: 'image', src: '/media/projects/ui-regression-desktop.png', alt: 'AI UI 回归审计桌面报告', caption: '桌面视口：差异、语义原因与证据绑定' },
        { kind: 'image', src: '/media/projects/ui-regression-mobile.png', alt: 'AI UI 回归审计手机报告', caption: '手机视口：移动端遮挡定位' },
      ],
    },
  ],
  compactProjects: [
    { id: 'rag-knowledge-base', title: 'RAG Knowledge Base', period: '2026.05 - 2026.06', role: '个人项目开发者（AI 辅助）', summary: '文档与 URL 入库、混合检索、重排、引用闭环和固定评测。', result: 'Fresh 验证：87 passed、1 skipped。', stack: ['Python', 'Streamlit', 'Chroma', 'BM25', 'Firecrawl'] },
    { id: 'codex-project-memory', title: 'Codex 项目长期记忆与 MCP', period: '2026.07', role: '需求与验收主导，Codex 实现', summary: '以 PROJECT、STATE、DECISIONS、JOURNAL 为单一事实源，支持恢复、原子写入和漂移评测。', result: 'Fresh 验证：178 passed、5 skipped、143 subtests passed。', stack: ['Python', 'Markdown', 'MCP', 'Pytest', 'uv'] },
    { id: 'birthday-site', title: '生日宇宙祝福站', period: '2026.05', role: '个人全栈项目开发者', summary: '祝福墙、所有者管理、软删除 / 恢复、操作审计与本地降级。', result: '生产构建通过；主包 621.20 kB，保留拆包优化项。', stack: ['React', 'Vite', 'Supabase', 'Express', 'TypeScript'] },
  ],
  skillGroups: [
    { label: '语言', items: ['Python', 'TypeScript', 'JavaScript'] },
    { label: 'AI / RAG', items: ['Qdrant', 'Chroma', 'Embedding', 'BM25', 'Reranker', '引用式回答'] },
    { label: '应用开发', items: ['FastAPI', 'React', 'Vite', 'Streamlit', 'Supabase'] },
    { label: '工程与质量', items: ['Git', 'Docker', 'Pytest', 'Vitest', 'Playwright', 'PyInstaller'] },
  ],
  about: '湖南大学建筑学本科在读。建筑训练带来空间分析、调研和视觉表达基础，并持续把这些能力用于 AI 应用工程。',
}
