import { agentReplay } from './agentReplay'
import type { PortfolioData } from './types'

export const portfolioData: PortfolioData = {
  person: {
    name: '磨海清',
    role: 'RAG / Agent 应用工程实习生',
    headline: '把 AI 原型做成可验证的产品。',
    introduction: '专注本地优先 RAG、Agent 与 AI 全栈应用，从检索质量推进到桌面交付。',
    email: '3230390742@qq.com',
    githubUrl: 'https://github.com/3230390742',
    resumeUrl: '/resume/磨海清_AI应用工程实习简历.pdf',
  },
  heroMetrics: [
    { value: '3,827', label: '知识分块', source: '内容模型声明', note: '本轮未独立运行' },
    { value: '0.084s', label: '启动扫描', source: '内容模型声明', note: '本轮未独立运行' },
    {
      value: `${agentReplay.verification.testsPassed}/${agentReplay.verification.testsTotal}`,
      label: 'MCP 测试记录',
      source: '历史运行产物',
      note: '本轮未重跑',
    },
  ],
  featuredProjects: [
    {
      id: 'personal-rag',
      title: 'Personal RAG Desktop',
      status: '本地静态核验',
      period: '2026.06 - 至今',
      role: '个人项目负责人',
      summary: '围绕 Obsidian Vault 构建 local-only 双 profile 知识库，本地源码包含 React + FastAPI 桌面壳，以及 PyInstaller 打包入口与实现代码。',
      problem: '研究资料与个人记忆需要统一检索，但个人内容必须保持 local-only，且桌面应用需要覆盖真实 Windows 生命周期。',
      constraints: ['个人记忆不得离开本机', '中文检索需要混合召回与重排', '安装、升级与卸载需要独立验证'],
      decisions: ['按 ai_research / personal_memory 划分 profile', '建立 Provider Client Pool 与 generation-safe 热重载', '通过 SSE 暴露 progress / timing 事件'],
      implementation: ['多格式解析、混合检索、重排和来源引用', 'React + FastAPI 桌面壳与 PyInstaller 打包', '前后端、隐私和真实启动质量门'],
      results: [
        { value: '175 → 164', label: '输入审核与合格记忆', source: '内容模型声明', note: '本轮未独立运行' },
        { value: '3,827', label: '最终分块', source: '内容模型声明', note: '本轮未独立运行' },
        { value: '7.44s → 0.084s', label: '启动扫描优化', source: '内容模型声明', note: '本轮未独立运行' },
        { value: '5 次', label: '生命周期记录', source: '内容模型声明', note: '本轮未独立运行' },
      ],
      verification: {
        source: '本地代码验证',
        runtimeStatus: '真实 Vault、构建产物、安装包和运行结果本轮未核验',
        publicBoundary: '个人记忆、向量库、私有评测集和 API key 不公开',
      },
      stack: ['Python', 'FastAPI', 'Qdrant', 'React', 'Vite', 'PyInstaller'],
      evidence: ['本地代码结构审查', '内容模型中的历史数字', '公开媒体素材'],
      visuals: [
        { kind: 'image', src: '/media/projects/personal-rag-ai-research.png', alt: 'Personal RAG Desktop 的 AI research 界面', caption: 'AI research profile：检索、来源与运行状态' },
        { kind: 'image', src: '/media/projects/personal-rag-memory.png', alt: 'Personal RAG Desktop 的 personal memory 界面', caption: 'Personal memory profile：local-only 记忆管理' },
        { kind: 'video', src: '/media/projects/personal-rag-demo.mp4', poster: '/media/projects/personal-rag-ai-research.png', title: 'Personal RAG Desktop 演示', caption: '本地应用与知识检索演示素材' },
      ],
    },
    {
      id: 'local-agent-mcp',
      title: 'Local Agent MCP',
      status: '已公开源码',
      period: '2026.07',
      role: '个人项目主导（AI 辅助）',
      summary: '实现包含运行、对比、健康检查和安全审计四类工具的本地 stdio MCP Agent Hub。',
      problem: '本地编排器需要调用多个编码 Agent，但工作目录、并发、输出和密钥边界不能依赖调用者自觉。',
      constraints: ['默认只读', '不得通过 shell 插值执行命令', '同目录写操作必须串行'],
      decisions: ['realpath allowlist 校验真实路径', '固定 shell:false 并限制输出与超时', '同目录写锁与全局并发限制组合'],
      implementation: ['Codex / OpenCode 运行与结果对比工具', '健康检查与结构化 Zod 输入', '密钥脱敏、超时和输出上限'],
      results: [
        { value: '4 类', label: 'MCP 工具', source: '公开仓库验证', note: '公开源码可核对' },
        {
          value: `${agentReplay.verification.testFilesPassed}/${agentReplay.verification.testFilesTotal}`,
          label: '测试文件记录',
          source: '历史运行产物',
          note: '本轮未重跑',
        },
        {
          value: `${agentReplay.verification.testsPassed}/${agentReplay.verification.testsTotal}`,
          label: '测试记录',
          source: '历史运行产物',
          note: '本轮未重跑',
        },
        { value: agentReplay.verification.typecheck, label: 'TypeScript typecheck 记录', source: '历史运行产物', note: '本轮未重跑' },
      ],
      verification: {
        source: '公开仓库验证',
        runtimeStatus: '公开 manifest 和 receipt 是历史运行记录',
        publicBoundary: '凭证、私有路径、密钥和未发布日志不公开',
      },
      stack: ['TypeScript', 'MCP SDK', 'Zod', 'Vitest', 'Node.js'],
      evidence: ['公开仓库源码', '历史 manifest 与 publication receipt', '安全边界测试定义'],
      repositoryUrl: 'https://github.com/3230390742/local-agent-mcp',
      visuals: [{ kind: 'agent-replay', title: 'Local Agent MCP 历史运行回放' }],
    },
    {
      id: 'ai-ui-regression',
      title: 'AI UI 回归审计',
      status: '本地静态核验',
      period: '2026.07',
      role: '证据链与实现负责人',
      summary: '结合真实浏览器截图、像素差、DOM 语义、布局几何和对比度规则审计两版界面。',
      problem: '纯截图差异无法可靠解释按钮缺失、语义漂移或移动端遮挡，检测器还必须与 private-truth 隔离。',
      constraints: ['全流程本地且零外联', '检测器与私有真值隔离', '每个 finding 必须绑定公开像素与语义证据'],
      decisions: ['Playwright 双视口确定性捕获', '像素差与通用语义规则组合', 'findings 锁定后再读取私有真值终审'],
      implementation: ['桌面与手机基线 / 候选捕获', '六类语义、布局和对比度检测', '自包含离线交互报告与哈希审计'],
      results: [
        { value: '6/6', label: '单原因回归记录', source: '本地代码验证', note: '本轮未执行端到端流水线' },
        { value: '0', label: '允许变化误报记录', source: '本地代码验证', note: '本轮未执行端到端流水线' },
        { value: '1.0', label: 'Precision / Recall / F1 记录', source: '本地代码验证', note: '本轮未执行端到端流水线' },
      ],
      verification: {
        source: '本地代码验证',
        runtimeStatus: '本轮未发现 FINAL_AUDIT_OK 产物',
        publicBoundary: 'private-truth 和会泄露答案的变异映射不公开',
      },
      stack: ['Python', 'Playwright', 'Pixel Diff', 'DOM', 'WCAG'],
      evidence: ['本地代码结构', '公开 findings 与差异区域', '本轮未执行端到端流水线'],
      visuals: [
        { kind: 'image', src: '/media/projects/ui-regression-desktop.png', alt: 'AI UI 回归审计桌面报告', caption: '桌面视口：差异、语义原因与证据绑定' },
        { kind: 'image', src: '/media/projects/ui-regression-mobile.png', alt: 'AI UI 回归审计手机报告', caption: '手机视口：移动端遮挡定位' },
      ],
    },
    {
      id: 'birthday-site',
      title: '生日宇宙',
      status: '已公开基础版',
      period: '2026.05',
      role: '个人全栈项目开发者',
      summary: '公开 main 是使用 Express、Supabase 和基础失败回退实现的基础祝福墙。',
      problem: '公开祝福需要可提交、可查看，并在后端暂时不可用时提供明确的基础失败回退。',
      constraints: ['公开案例只描述公开 main', '高级本地能力不得冒充公开版本', '服务角色密钥和真实祝福数据不得公开'],
      decisions: ['公开 main 保持基础祝福墙范围', 'Supabase 负责公开数据持久化', '基础失败回退明确提示服务状态'],
      implementation: [
        '公开 main：Express API、Supabase 持久化与基础失败回退',
        '本地代码验证：所有者管理、软删除、恢复、操作审计与增强 localStorage 降级',
        '本地高级实现尚未进入公开 main',
      ],
      results: [
        { value: '公开基础版', label: '公开 main', source: '公开仓库验证', note: '基础祝福墙范围' },
        { value: '本地高级实现', label: '本地分支', source: '本地代码验证', note: '未进入公开 main' },
        { value: '当前未部署', label: '自有域名', source: '需要本人确认', note: 'www.mohaiqing.top 不能作为在线演示' },
      ],
      verification: {
        source: '公开仓库验证',
        runtimeStatus: 'www.mohaiqing.top 未部署，当前不能作为在线演示',
        publicBoundary: 'Supabase 服务角色密钥和真实祝福数据不公开',
      },
      stack: ['React', 'Vite', 'Supabase', 'Express', 'TypeScript'],
      evidence: ['公开 main 基础祝福墙', '本地高级实现未进入公开 main', '自有域名未部署'],
      visuals: [{
        kind: 'evidence',
        title: '版本证据',
        lines: ['公开 main 基础祝福墙', '本地高级实现未进入公开 main', '自有域名未部署'],
      }],
      repositoryUrl: 'https://github.com/3230390742/birthday-cyber-wishes',
    },
  ],
  compactProjects: [
    {
      id: 'rag-knowledge-base',
      title: 'RAG Knowledge Base',
      period: '2026.05 - 2026.06',
      role: '个人项目开发者（AI 辅助）',
      summary: '独立公开项目：文档与 URL 入库、混合检索、重排、引用闭环和固定评测。',
      result: '内容模型记录：87 passed、1 skipped。',
      source: '公开仓库验证',
      verificationNote: '评测数字来自内容模型声明，本轮未重跑',
      resultSource: '内容模型声明',
      resultNote: '本轮未重跑',
      stack: ['Python', 'Streamlit', 'Chroma', 'BM25', 'Firecrawl'],
    },
    {
      id: 'codex-project-memory',
      title: 'Codex 项目长期记忆与 MCP',
      period: '2026.07',
      role: '需求与验收主导，Codex 实现',
      summary: '以 PROJECT、STATE、DECISIONS、JOURNAL 为单一事实源，支持恢复、原子写入和漂移评测。',
      result: '内容模型记录：178 passed、5 skipped、143 subtests passed。',
      source: '内容模型声明',
      verificationNote: '本轮未重跑',
      resultSource: '内容模型声明',
      resultNote: '本轮未重跑',
      stack: ['Python', 'Markdown', 'MCP', 'Pytest', 'uv'],
    },
  ],
  skillGroups: [
    { label: '语言', items: ['Python', 'TypeScript', 'JavaScript'] },
    { label: 'AI / RAG', items: ['Qdrant', 'Chroma', 'Embedding', 'BM25', 'Reranker', '引用式回答'] },
    { label: '应用开发', items: ['FastAPI', 'React', 'Vite', 'Streamlit', 'Supabase'] },
    { label: '工程与质量', items: ['Git', 'Docker', 'Pytest', 'Vitest', 'Playwright', 'PyInstaller'] },
  ],
  about: '湖南大学建筑学本科在读。建筑训练带来空间分析、调研和视觉表达基础，并持续把这些能力用于 AI 应用工程。',
}
